---
# Preliminary tasks.
- name: "PRELIM | Set gpg_key_url for Red Hat"
  set_fact:
      gpg_key_url: https://www.redhat.com/security/fd431d51.txt
  when: "ansible_distribution == 'RedHat'"
  always_run: yes

- name: "PRELIM | List users accounts"
  command: "awk -F: '{print $1}' /etc/passwd"
  register: users
  changed_when: false
  always_run: yes

- name: "PRELIM | Identify Unlocked Accounts"
  shell: >
      awk -F: '$1 !~ /^root$/ && $2 !~ /^[!*]/ {print $1}' /etc/shadow
  register: unlocked_accounts
  changed_when: false
  always_run: yes

- name: "PRELIM | Identify Unlocked Sys Accounts"
  shell: >
      awk -F: '$1 !~ /^root$/ && $2 !~ /^[!*]/ {print $1}' /etc/shadow | xargs -I{} grep {} /etc/passwd | awk -F: '$3 < 500 {print $1}'
  register: unlocked_sys_accounts
  changed_when: false
  always_run: yes

- name: "PRELIM | List system accounts"
  shell: "grep -Ev '/home|root' /etc/passwd | cut -d : -f 1"
  register: system_users
  changed_when: false
  always_run: yes

- include: version.yml
