---
- include: version.yml

- name: "HIGH | RHEL-07-010010 | AUDIT | The file permissions, ownership, and group membership of system files and commands must match the vendor values."
  shell: 'rpm -Va | grep ''^.M'''
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_010010_audit

- name: "HIGH | RHEL-07-010010 | FIX | The file permissions, ownership, and group membership of system files and commands must match the vendor values."
  shell: 'rpm --setperms $(rpm -qf {{ item.split('' '')[-1] }}); rpm --setugids $(rpm -qf {{ item.split('' '')[-1] }})'
  with_items: "{{ rhel_07_010010_audit.stdout_lines }}"
  when: rhel_07_010010_audit.stdout_lines | length > 0

- name: "HIGH | RHEL-07-010020 | AUDIT | The cryptographic hash of system files and commands must match vendor values."
  shell: 'rpm -Va | grep ''^..5'' | grep -E ''/.?bin/'''
  failed_when: no
  changed_when: no
  ignore_errors: yes
  register: rhel_07_010020_audit

- name: "HIGH | RHEL-07-010020 | FIX | The cryptographic hash of system files and commands must match vendor values."
  shell: yum reinstall -y $(rpm -qf {{ item.split(' ')[-1] }})
  with_items: "{{ rhel_07_010020_audit.stdout_lines }}"
  when: rhel_07_010020_audit.stdout_lines | length > 0

